default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: job_matching_app_development

test:
  <<: *default
  database: job_matching_app_test

production:
  <<: *default
  database: job_matching_app_production
  username: job_matching_app
  password: <%= ENV['JOB_MATCHING_APP_DATABASE_PASSWORD'] %>
